network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
         dhcp4: true
         match:
           macaddress: 02:e9:99:ad:26:c9
         set-name: enp0s3
    enp0s8:
      addresses: [192.168.13.230/24]
      gateway4: 192.168.13.1
      nameservers:
           addresses: [8.8.8.8, 1.1.1.1]
    enp0s9:
      addresses: [192.168.102.10/24]
      gateway4: 192.168.102.1