
network:
  version: 2
  ethernets:
    enp0s8:
      addresses: [192.168.102.11/24]
      gateway4: 192.168.102.1
      routes:
      # - to : default
      #   via: 192.168.102.1
        to: [0.0.0.0/0]
        via: 192.168.102.10
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]

    enp0s9:
      addresses: [192.168.100.2/24]
      routes:
      - to : 192.168.101.0/24
        via: 192.168.100.2

  

