- hosts: apache
  any_errors_fatal: true
  become: yes
  roles:
    - role: mrlesmithjr.netplan
      become: yes
      # This role will do nothing unless netplan_enabled is true.
      netplan_enabled: true
      
      # This should point to an existing netplan configuration file 
      # on your system which this role will overwrite, 
      # or to a nonexistent file which netplan is aware of.
      #
      # The default is /etc/netplan/config.yaml.
      netplan_config_file: /etc/netplan/50-vagrant.yaml
      
      # Ubuntu 18.04, for example, defaults to using networkd.
      netplan_renderer: networkd
      # Simple network configuration to add a single network interface.
      # Configuration defined bellow will be written to the file defined
      # above in `netplan_config_file`.
      netplan_configuration:
        network:
          version: 2
          renderer: networkd
          ethernets:
            enp0s3:
              addresses: [10.0.2.15/24]
              routes:
              - to : 10.0.2.0/24
                via: 10.0.2.2
              # dhcp4: true
              # match:
              #   macaddress: 02:e9:99:ad:26:c9
              # set-name: enp0s3
            enp0s8:
              addresses: [192.168.102.11/24]
              # gateway4: 192.168.102.1
              routes:
              - to : default
                via: 192.168.102.1
              - to : 192.168.13.0/24
                via: 192.168.102.10
              nameservers:
                addresses: [8.8.8.8, 1.1.1.1]

            enp0s9:
              addresses: [192.168.100.2/24]
              routes:
              - to : 192.168.101.0/24
                via: 192.168.100.3
  tasks:
  - name: Apply netplan
    command: sudo netplan apply
    async: 10
    poll: 0
  - name: install Apache
    become: yes
    ansible.builtin.apt:
      name: 
       - apache2
       - mysql-client
       - ghostscript
       - ghostscript
       - libapache2-mod-php
       - php
       - php-curl
       - php-gd
       - php-json
       - php-mbstring
       - php-mysql
       - php-xmlrpc
       - php-xml
       - php-soap
       - php-cgi
       - php-dom
       - php-intl
       - php-zip
      update_cache: yes
      state: latest
  - name: start Apache
    ansible.builtin.systemd:
      name: apache2
      state: restarted
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /srv/www/
      state: directory
      mode: '0755' 
  - name: Change file ownership, group and permissions
    ansible.builtin.file:
      path: /srv/www/
      owner: www-data
      group: www-data
      mode: '755'
      recurse: yes       
  - name: Download Wordpress
    unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: /srv/www/
      remote_src: True    
  - name: Copy Wordpress Conf
    ansible.builtin.copy:
      src: "./wp-config.php"
      dest: "/srv/www/wordpress/wp-config.php"
  - name: Change file ownership, group and permissions
    ansible.builtin.file:
      path: /var/www/wordpress/
      owner: www-data
      group: www-data
      mode: '755'
      recurse: yes
  - name: Copy Apache conf2
    ansible.builtin.template:
      src: "./wordpress.conf"
      dest: "/etc/apache2/sites-available/wordpress.conf"       
  - name: Enable new site
    become: yes
    shell: sudo /usr/sbin/a2ensite wordpress
  - name: Enable rewrite
    shell: a2enmod rewrite 
  - name: Disable default modules for Debian
    community.general.apache2_module:
      state: absent
      name: 000-default
      force: true    
  - name: Reload Apache
    ansible.builtin.systemd:
      name: apache2
      state: restarted